# Generated by Django 5.1.7 on 2025-04-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.faculty",
            ),
        ),
    ]
