# Generated by Django 5.1.7 on 2025-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_level"),
        ("lms", "0015_alter_classroomannouncement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favourite_courses",
            field=models.ManyToManyField(
                blank=True, related_name="favourite_courses", to="lms.course"
            ),
        ),
    ]
