# Generated by Django 5.1.7 on 2025-04-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_task_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="points_possible",
            new_name="total_points",
        ),
    ]
