# Generated by Django 5.1.7 on 2025-04-08 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_classroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "Student"},
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
