# Generated by Django 5.1.7 on 2025-04-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_content_created_at_content_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='text',
            name='created',
        ),
        migrations.RemoveField(
            model_name='text',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
    ]
