# Generated by Django 5.1.7 on 2025-04-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_task_taskattachment_studenttaskprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allowed_file_types',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('ppt', 'PPT'), ('url', 'url')], help_text='Select all allowed file extensions (e.g., pdf,docx)', max_length=255),
        ),
    ]
