# Generated by Django 5.1.7 on 2025-04-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_alter_tasksubmission_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksubmission",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
    ]
