# Generated by Django 5.1.7 on 2025-04-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_task_allowed_file_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('ext', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='allowed_file_types',
        ),
        migrations.AddField(
            model_name='task',
            name='allowed_file_types',
            field=models.ManyToManyField(blank=True, help_text='Select all allowed file extensions (e.g., pdf,docx)', to='lms.filetype'),
        ),
    ]
