# Generated by Django 5.1.7 on 2025-04-10 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0012_tasksubmission_is_graded"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksubmission",
            name="submission_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
