# Generated by Django 5.1.7 on 2025-04-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_filetype_remove_task_allowed_file_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetype',
            old_name='file_type',
            new_name='name',
        ),
    ]
