# Generated by Django 5.1.7 on 2025-05-01 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0016_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
