# Generated by Django 5.1.7 on 2025-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0019_question_option_quiz_quizquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
    ]
