# Generated by Django 5.1.7 on 2025-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0020_alter_option_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="text_words",
            field=models.TextField(default="vbvbn"),
            preserve_default=False,
        ),
    ]
