# Generated by Django 5.1.7 on 2025-05-20 17:26

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0021_option_text_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
